#!/bin/bash

#Submit this script with: sbatch calibrate_script

#SBATCH --time=100:00:00   # walltime
#SBATCH --ntasks=1         # number of processor cores (i.e. tasks)
#SBATCH --nodes=1          # number of nodes
#SBATCH --gres gpu:1
#SBATCH --mem-per-cpu=64G
#SBATCH -J "NN-10000-100"    # job name
#SBATCH --output=10000-100.out  

echo "NN-10000"

M=10000
N_neurons=512
width=32

cd FNO
python -u learnFNO.py      $(M)  $(width)  > $(M)-$(width).out 
python -u evalFNO.py       $(M)  $(width)  > $(M)-$(width).out 
cd ../PCA  
python -u learnPCA.py      $(M)  $(N_neurons) > $(M)-$(N_neurons).out
python -u evalPCA.py       $(M)  $(N_neurons) > $(M)-$(N_neurons).out
cd ../PARA
python -u learnPARA.py     $(M)  $(N_neurons) > $(M)-$(N_neurons).out
python -u evalPARA.py      $(M)  $(N_neurons) > $(M)-$(N_neurons).out
cd ../DeepONet
python -u learnDeepONet.py $(M)  $(N_neurons) > $(M)-$(N_neurons).out
python -u evalDeepONet.py  $(M)  $(N_neurons) > $(M)-$(N_neurons).out
