#!/bin/bash

#Submit this script with: sbatch calibrate_script

#SBATCH --time=1:00:00   # walltime
#SBATCH --ntasks=1         # number of processor cores (i.e. tasks)
#SBATCH --nodes=1          # number of nodes
#SBATCH --gres gpu:1
#SBATCH --mem-per-cpu=64G
#SBATCH -J "Map-Plot"    # job name
#SBATCH --output=Map-Plot.out  



M=20000
N_neurons=128
width=16

cd PCA  
python -u evalPCA.py       $M  $N_neurons 4 16 > $M-$N_neurons-test.out

cd ../FNO 
python -u evalFNO.py       $M  $width  16 > $M-$width-test.out 

cd ../DeepONet
python -u evalDeepFFONet.py  $M  $N_neurons 4 16 > $M-$N_neurons-test.out

cd ../PARA
python -u evalPARA.py       $M  $N_neurons > $M-$N_neurons-test.out 

